services:

  _defaults:
    autowire: false
    autoconfigure: false
    public: true

  ProjetNormandie\MessageBundle\Controller\User\GetNbNewMessage:
    arguments:
      - '@pn.message.repository.message'
      - '@event_dispatcher'
    calls:
      - [ setContainer, [ "@service_container" ] ]

  ProjetNormandie\MessageBundle\Controller\User\GetRecipients:
    arguments:
      - '@pn.message.repository.message'
    calls:
      - [ setContainer, [ "@service_container" ] ]

  ProjetNormandie\MessageBundle\Controller\User\GetSenders:
    arguments:
      - '@pn.message.repository.message'
    calls:
      - [ setContainer, [ "@service_container" ] ]