services:
    pn.message.event.entity.message:
        class: ProjetNormandie\MessageBundle\EventListener\Entity\MessageListener
        arguments:
            - '@security.helper'
        tags:
            - { name: doctrine.orm.entity_listener }




