services:
    pn.message.repository.message:
        class: ProjetNormandie\MessageBundle\Repository\MessageRepository
        factory: [ '@doctrine.orm.dwh_entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\MessageBundle\Entity\Message
