services:
    sonata.admin.message.message:
        class: ProjetNormandie\MessageBundle\Admin\MessageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.messages", label: "label.message" }
        arguments:
            - ~
            - ProjetNormandie\MessageBundle\Entity\Message
            - ~

