resources:
    ProjetNormandie\MessageBundle\Entity\Message:
        shortName: 'Message'
        collectionOperations:
            get:
                normalization_context: {'groups': [message_message_read]}
                pagination_items_per_page: 10
                filters : ['pn-message.filters']
            post:
                access_control: 'is_granted("ROLE_USER")'
        itemOperations:
            get: ~
            put:
                access_control: 'is_granted("ROLE_USER") and (object.getSender() == user or object.getRecipient() == user)'
