ProjetNormandie\MessageBundle\Entity\Message:
  attributes:
    id:
      groups:
        - 'message.read'
        - 'message.put'
    object:
      groups:
        - 'message.read'
        - 'message.post'
    type:
      groups:
        - 'message.read'
    message:
      groups:
        - 'message.read'
        - 'message.post'
    sender:
      groups:
        - 'message.read'
        - 'message.post'
    recipient:
      groups:
        - 'message.read'
        - 'message.post'
    isOpened:
      groups:
        - 'message.read'
        - 'mmessage.put'
    isDeletedSender:
      groups:
        - 'message.read'
        - 'message.put'
    isDeletedRecipient:
      groups:
        - 'message.read'
        - 'message.put'
    createdAt:
      groups:
        - 'message.read'
    updatedAt:
      groups: []


