ProjetNormandie\MessageBundle\Entity\Message:
  attributes:
    id:
      groups:
        - 'message_message_read'
        - 'message_message_put'
    object:
      groups:
        - 'message_message_read'
    type:
      groups:
        - 'message_message_read'
    message:
      groups:
        - 'message_message_read'
    sender:
      groups:
        - 'message_message_read'
    recipient:
      groups:
        - 'message_message_read'
    isOpened:
      groups:
        - 'message_message_read'
        - 'message_message_put'
    isDeletedSender:
      groups:
        - 'message_message_read'
        - 'message_message_put'
    isDeletedRecipient:
      groups:
        - 'message_message_read'
        - 'message_message_put'
    createdAt:
      groups:
        - 'message_message_read'
    updatedAt:
      groups: []


