resources:
    ProjetNormandie\MessageBundle\Entity\Message:
        shortName: 'Message'
        collectionOperations:
            get:
                access_control: 'is_granted("ROLE_USER")'
                normalization_context: {'groups': [message.read]}
                pagination_items_per_page: 10
            post:
                access_control: 'is_granted("ROLE_USER")'
                denormalization_context: {'groups': [message.post]}
                normalization_context: {'groups': [message.read]}
            get-recipients:
                access_control: 'is_granted("ROLE_USER")'
                method: 'GET'
                path: '/messages/get-recipients'
                controller: 'ProjetNormandie\MessageBundle\Controller\UserController::getRecipients'
            get-senders:
                access_control: 'is_granted("ROLE_USER")'
                method: 'GET'
                path: '/messages/get-senders'
                controller: 'ProjetNormandie\MessageBundle\Controller\UserController::getSenders'
        itemOperations:
            get:
                access_control: 'is_granted("ROLE_USER")'
                normalization_context: {'groups': [message.read]}
            put:
                access_control: 'is_granted("ROLE_USER") and (object.getSender() == user or object.getRecipient() == user)'
                denormalization_context: {'groups': [message.put]}
                normalization_context: {'groups': [message.read]}
