services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    pn.message.builder.message:
        class: ProjetNormandie\MessageBundle\Builder\MessageBuilder
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ProjetNormandie\MessageBundle\Command\PurgeCommand:
        class: ProjetNormandie\MessageBundle\Command\PurgeCommand
        arguments:
            - '@pn.message.repository.message'
        tags:
            - { name: 'console.command', command: 'pn-message:purge' }

    pn.message.event.entity.message:
        class: ProjetNormandie\MessageBundle\EventListener\Entity\MessageListener
        arguments:
            - '@security.helper'
        tags:
            - { name: doctrine.orm.entity_listener }

    pn.message.repository.message:
        class: ProjetNormandie\MessageBundle\Repository\MessageRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - ProjetNormandie\MessageBundle\Entity\Message
