services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    ProjetNormandie\MessageBundle\:
        resource: '../../*'
        exclude: '../../{Admin,DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    pn.message.builder.message:
        class: ProjetNormandie\MessageBundle\Builder\MessageBuilder
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ProjetNormandie\MessageBundle\Command\PurgeCommand:
        class: ProjetNormandie\MessageBundle\Command\PurgeCommand
        arguments:
            - '@pn.message.repository.message'
        tags:
            - { name: 'console.command', command: 'pn-message:purge' }

    ProjetNormandie\MessageBundle\Controller\UserController:
        arguments:
            - '@pn.message.repository.message'
        tags: [ 'controller.service_arguments' ]

    pn.message.event.entity.message:
        class: ProjetNormandie\MessageBundle\EventListener\Entity\MessageListener
        arguments:
            - '@security.helper'
        tags:
            - { name: doctrine.orm.entity_listener }

    pn.message.repository.message:
        class: ProjetNormandie\MessageBundle\Repository\MessageRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - ProjetNormandie\MessageBundle\Entity\Message
