services:
  sonata.admin.message.message:
    class: ProjetNormandie\MessageBundle\Admin\MessageAdmin
    tags:
      - name: sonata.admin
        model_class: 'ProjetNormandie\MessageBundle\Entity\Message'
        manager_type: orm
        group: "group.messages"
        label: "label.message"

