services:
  _defaults:
    autowire: true
    autoconfigure: true

  ProjetNormandie\MessageBundle\:
    resource: '../src/*'
    exclude: '../src/{Admin,Entity,DependencyInjection,Migrations,Tests,Kernel.php}'

  pn.message.event.entity.message:
    class: ProjetNormandie\MessageBundle\EventListener\Entity\MessageListener
    tags:
      - { name: doctrine.orm.entity_listener }

